update_interval: 5m
timeout: 20s
allow_anonymous: true
anonymous_alias: server001

credentials:
  - username: user1
    password: password1
  - username: user2
    password: password2

config_files:
  - ./dockerconfigauth.example.json
  - ./dockerconfiguserpassword.example.json
